name: Publish ❯ Package

on:
  # push:
  #   tags:
  #     - "v*"

  workflow_dispatch:
    {}
    # inputs:
    #   version:
    #     description: Version Number
    #     type: string
    #     required: true
    #   prerelease:
    #     description: Prerelease?
    #     type: boolean
    #     required: true
    #     default: true

concurrency:
  group: perform-release-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    name: Testing Matrix
    runs-on: ${{ matrix.os }}
    env:
      MIX_ENV: test

    continue-on-error: ${{ matrix.type == 'optional' }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - "ubuntu-24.04"
          - "ubuntu-22.04"
          # - "ubuntu-20.04" # Retired
          - "windows-2025"
          - "windows-2022"
          - "macOS-15"
          - "macOS-14"
          # - "macOS-13" # Retired
        elixir:
          - "1.19.x"
        otp:
          - "28.x"
          - "27.x"
          - "26.x"
        type: [required]
        include:
          ####
          # Other versions we want to check
          # See Elixir versions: https://github.com/elixir-lang/elixir/blob/main/lib/elixir/pages/references/compatibility-and-deprecations.md
          # and beam-setup versions: https://github.com/erlef/setup-beam?tab=readme-ov-file#compatibility-between-operating-system-and-erlangotp
          ##

          ####
          # SECURITY PATCH ELIXIRS
          ##

          # ELIXIR 1.18 (OTP 27-25)
          - elixir: "1.18.x"
            otp: "27.x"
            os: "ubuntu-24.04"
            type: required
          - elixir: "1.18.x"
            otp: "27.x"
            os: "ubuntu-22.04"
            type: required
          - elixir: "1.18.x"
            otp: "27.x"
            os: "windows-2025"
            type: required
          - elixir: "1.18.x"
            otp: "27.x"
            os: "windows-2022"
            type: required
          - elixir: "1.18.x"
            otp: "27.x"
            os: "macOS-15"
            type: required
          - elixir: "1.18.x"
            otp: "27.x"
            os: "macOS-14"
            type: required
          - elixir: "1.18.x"
            otp: "26.x"
            os: "ubuntu-24.04"
            type: required
          - elixir: "1.18.x"
            otp: "26.x"
            os: "ubuntu-22.04"
            type: required
          - elixir: "1.18.x"
            otp: "26.x"
            os: "windows-2025"
            type: required
          - elixir: "1.18.x"
            otp: "26.x"
            os: "windows-2022"
            type: required
          - elixir: "1.18.x"
            otp: "26.x"
            os: "macOS-15"
            type: required
          - elixir: "1.18.x"
            otp: "26.x"
            os: "macOS-14"
            type: required
          - elixir: "1.18.x"
            otp: "25.x"
            os: "ubuntu-24.04"
            type: required
          - elixir: "1.18.x"
            otp: "25.x"
            os: "ubuntu-22.04"
            type: required
          - elixir: "1.18.x"
            otp: "25.x"
            os: "windows-2025"
            type: required
          - elixir: "1.18.x"
            otp: "25.x"
            os: "windows-2022"
            type: required
          - elixir: "1.18.x"
            otp: "25.x"
            os: "macOS-15"
            type: required
          - elixir: "1.18.x"
            otp: "25.x"
            os: "macOS-14"
            type: required

          # ELIXIR 1.17 (OTP 27-25)
          - elixir: "1.17.x"
            otp: "27.x"
            os: "ubuntu-24.04"
            type: required
          - elixir: "1.17.x"
            otp: "27.x"
            os: "ubuntu-22.04"
            type: required
          - elixir: "1.17.x"
            otp: "27.x"
            os: "windows-2025"
            type: required
          - elixir: "1.17.x"
            otp: "27.x"
            os: "windows-2022"
            type: required
          - elixir: "1.17.x"
            otp: "27.x"
            os: "macOS-15"
            type: required
          - elixir: "1.17.x"
            otp: "27.x"
            os: "macOS-14"
            type: required
          - elixir: "1.17.x"
            otp: "26.x"
            os: "ubuntu-24.04"
            type: required
          - elixir: "1.17.x"
            otp: "26.x"
            os: "ubuntu-22.04"
            type: required
          - elixir: "1.17.x"
            otp: "26.x"
            os: "windows-2025"
            type: required
          - elixir: "1.17.x"
            otp: "26.x"
            os: "windows-2022"
            type: required
          - elixir: "1.17.x"
            otp: "26.x"
            os: "macOS-15"
            type: required
          - elixir: "1.17.x"
            otp: "26.x"
            os: "macOS-14"
            type: required
          - elixir: "1.17.x"
            otp: "25.x"
            os: "ubuntu-24.04"
            type: required
          - elixir: "1.17.x"
            otp: "25.x"
            os: "ubuntu-22.04"
            type: required
          - elixir: "1.17.x"
            otp: "25.x"
            os: "windows-2025"
            type: required
          - elixir: "1.17.x"
            otp: "25.x"
            os: "windows-2022"
            type: required
          - elixir: "1.17.x"
            otp: "25.x"
            os: "macOS-15"
            type: required
          - elixir: "1.17.x"
            otp: "25.x"
            os: "macOS-14"
            type: required

          ##
          # OTPs <25 below this aren't available on macOS images
          ##

          # ELIXIR 1.16 (OTP 26-24)
          - elixir: "1.16.x"
            otp: "26.x"
            os: "ubuntu-24.04"
            type: required
          - elixir: "1.16.x"
            otp: "26.x"
            os: "ubuntu-22.04"
            type: required
          - elixir: "1.16.x"
            otp: "26.x"
            os: "windows-2025"
            type: required
          - elixir: "1.16.x"
            otp: "26.x"
            os: "windows-2022"
            type: required
          - elixir: "1.16.x"
            otp: "26.x"
            os: "macOS-15"
            type: required
          - elixir: "1.16.x"
            otp: "26.x"
            os: "macOS-14"
            type: required
          - elixir: "1.16.x"
            otp: "25.x"
            os: "ubuntu-24.04"
            type: required
          - elixir: "1.16.x"
            otp: "25.x"
            os: "ubuntu-22.04"
            type: required
          - elixir: "1.16.x"
            otp: "25.x"
            os: "windows-2025"
            type: required
          - elixir: "1.16.x"
            otp: "25.x"
            os: "windows-2022"
            type: required
          - elixir: "1.16.x"
            otp: "25.x"
            os: "macOS-15"
            type: required
          - elixir: "1.16.x"
            otp: "25.x"
            os: "macOS-14"
            type: required
          - elixir: "1.16.x"
            otp: "24.x"
            os: "ubuntu-24.04"
            type: required
          - elixir: "1.16.x"
            otp: "24.x"
            os: "ubuntu-22.04"
            type: required
          - elixir: "1.16.x"
            otp: "24.x"
            os: "windows-2025"
            type: required
          - elixir: "1.16.x"
            otp: "24.x"
            os: "windows-2022"
            type: required

          ##
          # Elixirs above this aren't available on ubuntu-20.04
          ##

          # ELIXIR 1.15 (OTP 26-24)
          - elixir: "1.15.x"
            otp: "26.x"
            os: "ubuntu-24.04"
            type: required
          - elixir: "1.15.x"
            otp: "26.x"
            os: "ubuntu-22.04"
            type: required
          - elixir: "1.15.x"
            otp: "26.x"
            os: "ubuntu-20.04"
            type: required
          - elixir: "1.15.x"
            otp: "26.x"
            os: "windows-2025"
            type: required
          - elixir: "1.15.x"
            otp: "26.x"
            os: "windows-2022"
            type: required
          - elixir: "1.15.x"
            otp: "26.x"
            os: "macOS-15"
            type: required
          - elixir: "1.15.x"
            otp: "26.x"
            os: "macOS-14"
            type: required
          - elixir: "1.15.x"
            otp: "25.x"
            os: "ubuntu-24.04"
            type: required
          - elixir: "1.15.x"
            otp: "25.x"
            os: "ubuntu-22.04"
            type: required
          - elixir: "1.15.x"
            otp: "25.x"
            os: "ubuntu-20.04"
            type: required
          - elixir: "1.15.x"
            otp: "25.x"
            os: "windows-2025"
            type: required
          - elixir: "1.15.x"
            otp: "25.x"
            os: "windows-2022"
            type: required
          - elixir: "1.15.x"
            otp: "25.x"
            os: "macOS-15"
            type: required
          - elixir: "1.15.x"
            otp: "25.x"
            os: "macOS-14"
            type: required
          - elixir: "1.15.x"
            otp: "24.x"
            os: "ubuntu-24.04"
            type: required
          - elixir: "1.15.x"
            otp: "24.x"
            os: "ubuntu-22.04"
            type: required
          - elixir: "1.15.x"
            otp: "24.x"
            os: "ubuntu-20.04"
            type: required
          - elixir: "1.15.x"
            otp: "24.x"
            os: "windows-2025"
            type: required
          - elixir: "1.15.x"
            otp: "24.x"
            os: "windows-2022"
            type: required

          ####
          # UNMAINTAINED ELIXIRS
          ##

          ##
          # OTPs <24 below this aren't available on ubuntu >20 images
          ##

          # ELIXIR 1.14 (OTP 26-23)
          - elixir: "1.14.x"
            otp: "26.x"
            os: "ubuntu-24.04"
            type: required
          - elixir: "1.14.x"
            otp: "26.x"
            os: "ubuntu-22.04"
            type: required
          - elixir: "1.14.x"
            otp: "26.x"
            os: "ubuntu-20.04"
            type: required
          - elixir: "1.14.x"
            otp: "26.x"
            os: "windows-2025"
            type: required
          - elixir: "1.14.x"
            otp: "26.x"
            os: "windows-2022"
            type: required
          - elixir: "1.14.x"
            otp: "26.x"
            os: "macOS-15"
            type: required
          - elixir: "1.14.x"
            otp: "26.x"
            os: "macOS-14"
            type: required
          - elixir: "1.14.x"
            otp: "25.x"
            os: "ubuntu-24.04"
            type: required
          - elixir: "1.14.x"
            otp: "25.x"
            os: "ubuntu-22.04"
            type: required
          - elixir: "1.14.x"
            otp: "25.x"
            os: "ubuntu-20.04"
            type: required
          - elixir: "1.14.x"
            otp: "25.x"
            os: "windows-2025"
            type: required
          - elixir: "1.14.x"
            otp: "25.x"
            os: "windows-2022"
            type: required
          - elixir: "1.14.x"
            otp: "25.x"
            os: "macOS-15"
            type: required
          - elixir: "1.14.x"
            otp: "25.x"
            os: "macOS-14"
            type: required
          - elixir: "1.14.x"
            otp: "24.x"
            os: "ubuntu-24.04"
            type: required
          - elixir: "1.14.x"
            otp: "24.x"
            os: "ubuntu-22.04"
            type: required
          - elixir: "1.14.x"
            otp: "24.x"
            os: "ubuntu-20.04"
            type: required
          - elixir: "1.14.x"
            otp: "24.x"
            os: "windows-2025"
            type: required
          - elixir: "1.14.x"
            otp: "24.x"
            os: "windows-2022"
            type: required
          - elixir: "1.14.x"
            otp: "23.x"
            os: "ubuntu-20.04"
            type: required
          - elixir: "1.14.x"
            otp: "23.x"
            os: "windows-2025"
            type: required
          - elixir: "1.14.x"
            otp: "23.x"
            os: "windows-2022"
            type: required

          # ELIXIR 1.13 (OTP 25-22)
          - elixir: "1.13.x"
            otp: "25.x"
            os: "ubuntu-24.04"
            type: required
          - elixir: "1.13.x"
            otp: "25.x"
            os: "ubuntu-22.04"
            type: required
          - elixir: "1.13.x"
            otp: "25.x"
            os: "ubuntu-20.04"
            type: required
          - elixir: "1.13.x"
            otp: "25.x"
            os: "windows-2025"
            type: required
          - elixir: "1.13.x"
            otp: "25.x"
            os: "windows-2022"
            type: required
          - elixir: "1.13.x"
            otp: "25.x"
            os: "macOS-15"
            type: required
          - elixir: "1.13.x"
            otp: "25.x"
            os: "macOS-14"
            type: required
          - elixir: "1.13.x"
            otp: "24.x"
            os: "ubuntu-24.04"
            type: required
          - elixir: "1.13.x"
            otp: "24.x"
            os: "ubuntu-22.04"
            type: required
          - elixir: "1.13.x"
            otp: "24.x"
            os: "ubuntu-20.04"
            type: required
          - elixir: "1.13.x"
            otp: "24.x"
            os: "windows-2025"
            type: required
          - elixir: "1.13.x"
            otp: "24.x"
            os: "windows-2022"
            type: required
          - elixir: "1.13.x"
            otp: "23.x"
            os: "ubuntu-20.04"
            type: required
          - elixir: "1.13.x"
            otp: "23.x"
            os: "windows-2025"
            type: required
          - elixir: "1.13.x"
            otp: "23.x"
            os: "windows-2022"
            type: required
          - elixir: "1.13.x"
            otp: "22.x"
            os: "ubuntu-20.04"
            type: required
          - elixir: "1.13.x"
            otp: "22.x"
            os: "windows-2025"
            type: required
          - elixir: "1.13.x"
            otp: "22.x"
            os: "windows-2022"
            type: required

          # ELIXIR 1.12 (OTP 24-22)
          - elixir: "1.12.x"
            otp: "24.x"
            os: "ubuntu-24.04"
            type: required
          - elixir: "1.12.x"
            otp: "24.x"
            os: "ubuntu-22.04"
            type: required
          - elixir: "1.12.x"
            otp: "24.x"
            os: "ubuntu-20.04"
            type: required
          - elixir: "1.12.x"
            otp: "24.x"
            os: "windows-2025"
            type: required
          - elixir: "1.12.x"
            otp: "24.x"
            os: "windows-2022"
            type: required
          - elixir: "1.12.x"
            otp: "23.x"
            os: "ubuntu-20.04"
            type: required
          - elixir: "1.12.x"
            otp: "23.x"
            os: "windows-2025"
            type: required
          - elixir: "1.12.x"
            otp: "23.x"
            os: "windows-2022"
            type: required
          - elixir: "1.12.x"
            otp: "22.x"
            os: "ubuntu-20.04"
            type: required
          - elixir: "1.12.x"
            otp: "22.x"
            os: "windows-2025"
            type: required
          - elixir: "1.12.x"
            otp: "22.x"
            os: "windows-2022"
            type: required

          ####
          # ORIGINAL TEST MATRIX
          #
          # Project was originally only tested on Elixir 1.10-1.11, OTP 22-23, so we should test back to then until a breaking release
          #  See: https://github.com/asummers/erlex/blob/0548765838a08583c83d72d208fde112104a3d2b/.github/workflows/pulls.yml#L11-L12
          # Project was originally claiming it supports back to Elixir 1.6, so we should test back to then until a breaking release
          #  See: https://github.com/asummers/erlex/blob/master/mix.exs#L11
          # OTP 21.x and older is retired in erlef/setup-beam, so we omit that in these matrices.
          ##

          # ELIXIR 1.11 (OTP 23-21)
          - elixir: "1.11.x"
            otp: "23.x"
            os: "ubuntu-20.04"
            type: required
          - elixir: "1.11.x"
            otp: "23.x"
            os: "windows-2025"
            type: required
          - elixir: "1.11.x"
            otp: "23.x"
            os: "windows-2022"
            type: required
          - elixir: "1.11.x"
            otp: "22.x"
            os: "ubuntu-20.04"
            type: required
          - elixir: "1.11.x"
            otp: "22.x"
            os: "windows-2025"
            type: required
          - elixir: "1.11.x"
            otp: "22.x"
            os: "windows-2022"
            type: required
          # Retired from erlef/setup-beam: OTP < 22.x
          # - elixir: "1.11.x"
          #   otp: "21.x"
          #   os: "ubuntu-20.04"
          #   type: required
          # - elixir: "1.11.x"
          #   otp: "21.x"
          #   os: "windows-2025"
          #   type: required
          # - elixir: "1.11.x"
          #   otp: "21.x"
          #   os: "windows-2022"
          #   type: required

          # ELIXIR 1.10 (OTP 23-21)
          - elixir: "1.10.x"
            otp: "23.x"
            os: "ubuntu-20.04"
            type: required
          - elixir: "1.10.x"
            otp: "23.x"
            os: "windows-2025"
            type: required
          - elixir: "1.10.x"
            otp: "23.x"
            os: "windows-2022"
            type: required
          - elixir: "1.10.x"
            otp: "22.x"
            os: "ubuntu-20.04"
            type: required
          - elixir: "1.10.x"
            otp: "22.x"
            os: "windows-2025"
            type: required
          - elixir: "1.10.x"
            otp: "22.x"
            os: "windows-2022"
            type: required
          # Retired from erlef/setup-beam: OTP < 22.x
          # - elixir: "1.10.x"
          #   otp: "21.x"
          #   os: "ubuntu-20.04"
          #   type: required
          # - elixir: "1.10.x"
          #   otp: "21.x"
          #   os: "windows-2025"
          #   type: required
          # - elixir: "1.10.x"
          #   otp: "21.x"
          #   os: "windows-2022"
          #   type: required

          ##
          # OTPs <21 below this aren't available on windows images
          ##

          # ELIXIR 1.9 (OTP 22-20)
          - elixir: "1.9.x"
            otp: "22.x"
            os: "ubuntu-20.04"
            type: required
          # Retired from erlef/setup-beam: OTP < 22.x
          # - elixir: "1.9.x"
          #   otp: "21.x"
          #   os: "ubuntu-20.04"
          #   type: required
          # - elixir: "1.9.x"
          #   otp: "20.x"
          #   os: "ubuntu-20.04"
          #   type: required

          # ELIXIR 1.8 (OTP 22-20)
          - elixir: "1.8.x"
            otp: "22.x"
            os: "ubuntu-20.04"
            type: required
          # Retired from erlef/setup-beam: OTP < 22.x
          # - elixir: "1.8.x"
          #   otp: "21.x"
          #   os: "ubuntu-20.04"
          #   type: required
          # - elixir: "1.8.x"
          #   otp: "20.x"
          #   os: "ubuntu-20.04"
          #   type: required

          ##
          # Elixirs below this point work on OTP < 20, which requires ubuntu-18.04
          #  which is no longer supported by GitHub actions, so we skip them
          ##

          # ELIXIR 1.7 (OTP 22-19)
          - elixir: "1.7.x"
            otp: "22.x"
            os: "ubuntu-20.04"
            type: required
          # Retired from erlef/setup-beam: OTP < 22.x
          # - elixir: "1.7.x"
          #   otp: "21.x"
          #   os: "ubuntu-20.04"
          #   type: required
          # - elixir: "1.7.x"
          #   otp: "20.x"
          #   os: "ubuntu-20.04"
          #   type: required

          # ELIXIR 1.6 (OTP 21-19)
          # Retired from erlef/setup-beam: OTP < 22.x
          # - elixir: "1.6.x"
          #   otp: "21.x"
          #   os: "ubuntu-20.04"
          #   type: required
          # - elixir: "1.6.x"
          #   otp: "20.x"
          #   os: "ubuntu-20.04"
          #   type: required

    steps:
      - uses: actions/checkout@v4

      - name: Install Erlang & Elixir
        id: beam-versions
        uses: erlef/setup-beam@v1
        with:
          elixir-version: ${{ matrix.elixir }}
          otp-version: ${{ matrix.otp }}

      - name: Restore mix dependency installation cache
        id: mix-deps-get-cache
        uses: actions/cache@v4
        with:
          path: |
            deps
            mix.lock
          key: cache-${{ vars.CACHE_VERSION }}-os-${{ runner.os }}-${{ steps.beam-versions.outputs.otp-version }}-${{ steps.beam-versions.outputs.elixir-version }}-mix-deps-get-mix-exs-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.exs')) }}

      - name: Install mix dependencies
        if: steps.mix-deps-get-cache.outputs.cache-hit != 'true'
        run: mix deps.get

      - name: Restore mix dependency compilation cache
        id: mix-deps-compile-cache
        uses: actions/cache@v4
        with:
          path: _build
          key: cache-${{ vars.CACHE_VERSION }}-os-${{ runner.os }}-otp-${{ steps.beam-versions.outputs.otp-version }}-elixir-${{ steps.beam-versions.outputs.elixir-version }}-env-${{ env.MIX_ENV }}-mix-deps-compile-mix-lock-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}

      - name: Compile mix dependencies
        if: steps.mix-deps-compile-cache.outputs.cache-hit != 'true'
        run: mix deps.compile

      - name: Run test suite
        run: mix test

  types:
    name: Typechecking Matrix
    runs-on: ${{ matrix.os }}
    env:
      MIX_ENV: test

    continue-on-error: ${{ matrix.type == 'optional' }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - "ubuntu-24.04"
          - "ubuntu-22.04"
          # - "ubuntu-20.04" # Retired
          - "windows-2025"
          - "windows-2022"
          - "macOS-15"
          - "macOS-14"
          # - "macOS-13" # Retired
        elixir:
          - "1.19.x"
        otp:
          - "28.x"
          - "27.x"
          - "26.x"
        type: [required]
        include:
          ####
          # Other versions we want to check
          # See Elixir versions: https://github.com/elixir-lang/elixir/blob/main/lib/elixir/pages/references/compatibility-and-deprecations.md
          # and beam-setup versions: https://github.com/erlef/setup-beam?tab=readme-ov-file#compatibility-between-operating-system-and-erlangotp
          ##

          ####
          # SECURITY PATCH ELIXIRS
          ##

          # ELIXIR 1.18 (OTP 27-25)
          - elixir: "1.18.x"
            otp: "27.x"
            os: "ubuntu-24.04"
            type: required
          - elixir: "1.18.x"
            otp: "27.x"
            os: "ubuntu-22.04"
            type: required
          - elixir: "1.18.x"
            otp: "27.x"
            os: "windows-2025"
            type: required
          - elixir: "1.18.x"
            otp: "27.x"
            os: "windows-2022"
            type: required
          - elixir: "1.18.x"
            otp: "27.x"
            os: "macOS-15"
            type: required
          - elixir: "1.18.x"
            otp: "27.x"
            os: "macOS-14"
            type: required
          - elixir: "1.18.x"
            otp: "26.x"
            os: "ubuntu-24.04"
            type: required
          - elixir: "1.18.x"
            otp: "26.x"
            os: "ubuntu-22.04"
            type: required
          - elixir: "1.18.x"
            otp: "26.x"
            os: "windows-2025"
            type: required
          - elixir: "1.18.x"
            otp: "26.x"
            os: "windows-2022"
            type: required
          - elixir: "1.18.x"
            otp: "26.x"
            os: "macOS-15"
            type: required
          - elixir: "1.18.x"
            otp: "26.x"
            os: "macOS-14"
            type: required
          - elixir: "1.18.x"
            otp: "25.x"
            os: "ubuntu-24.04"
            type: required
          - elixir: "1.18.x"
            otp: "25.x"
            os: "ubuntu-22.04"
            type: required
          - elixir: "1.18.x"
            otp: "25.x"
            os: "windows-2025"
            type: required
          - elixir: "1.18.x"
            otp: "25.x"
            os: "windows-2022"
            type: required
          - elixir: "1.18.x"
            otp: "25.x"
            os: "macOS-15"
            type: required
          - elixir: "1.18.x"
            otp: "25.x"
            os: "macOS-14"
            type: required

          # ELIXIR 1.17 (OTP 27-25)
          - elixir: "1.17.x"
            otp: "27.x"
            os: "ubuntu-24.04"
            type: required
          - elixir: "1.17.x"
            otp: "27.x"
            os: "ubuntu-22.04"
            type: required
          - elixir: "1.17.x"
            otp: "27.x"
            os: "windows-2025"
            type: required
          - elixir: "1.17.x"
            otp: "27.x"
            os: "windows-2022"
            type: required
          - elixir: "1.17.x"
            otp: "27.x"
            os: "macOS-15"
            type: required
          - elixir: "1.17.x"
            otp: "27.x"
            os: "macOS-14"
            type: required
          - elixir: "1.17.x"
            otp: "26.x"
            os: "ubuntu-24.04"
            type: required
          - elixir: "1.17.x"
            otp: "26.x"
            os: "ubuntu-22.04"
            type: required
          - elixir: "1.17.x"
            otp: "26.x"
            os: "windows-2025"
            type: required
          - elixir: "1.17.x"
            otp: "26.x"
            os: "windows-2022"
            type: required
          - elixir: "1.17.x"
            otp: "26.x"
            os: "macOS-15"
            type: required
          - elixir: "1.17.x"
            otp: "26.x"
            os: "macOS-14"
            type: required
          - elixir: "1.17.x"
            otp: "25.x"
            os: "ubuntu-24.04"
            type: required
          - elixir: "1.17.x"
            otp: "25.x"
            os: "ubuntu-22.04"
            type: required
          - elixir: "1.17.x"
            otp: "25.x"
            os: "windows-2025"
            type: required
          - elixir: "1.17.x"
            otp: "25.x"
            os: "windows-2022"
            type: required
          - elixir: "1.17.x"
            otp: "25.x"
            os: "macOS-15"
            type: required
          - elixir: "1.17.x"
            otp: "25.x"
            os: "macOS-14"
            type: required

          ##
          # OTPs <25 below this aren't available on macOS images
          ##

          # ELIXIR 1.16 (OTP 26-24)
          - elixir: "1.16.x"
            otp: "26.x"
            os: "ubuntu-24.04"
            type: required
          - elixir: "1.16.x"
            otp: "26.x"
            os: "ubuntu-22.04"
            type: required
          - elixir: "1.16.x"
            otp: "26.x"
            os: "windows-2025"
            type: required
          - elixir: "1.16.x"
            otp: "26.x"
            os: "windows-2022"
            type: required
          - elixir: "1.16.x"
            otp: "26.x"
            os: "macOS-15"
            type: required
          - elixir: "1.16.x"
            otp: "26.x"
            os: "macOS-14"
            type: required
          - elixir: "1.16.x"
            otp: "25.x"
            os: "ubuntu-24.04"
            type: required
          - elixir: "1.16.x"
            otp: "25.x"
            os: "ubuntu-22.04"
            type: required
          - elixir: "1.16.x"
            otp: "25.x"
            os: "windows-2025"
            type: required
          - elixir: "1.16.x"
            otp: "25.x"
            os: "windows-2022"
            type: required
          - elixir: "1.16.x"
            otp: "25.x"
            os: "macOS-15"
            type: required
          - elixir: "1.16.x"
            otp: "25.x"
            os: "macOS-14"
            type: required
          - elixir: "1.16.x"
            otp: "24.x"
            os: "ubuntu-24.04"
            type: required
          - elixir: "1.16.x"
            otp: "24.x"
            os: "ubuntu-22.04"
            type: required
          - elixir: "1.16.x"
            otp: "24.x"
            os: "windows-2025"
            type: required
          - elixir: "1.16.x"
            otp: "24.x"
            os: "windows-2022"
            type: required

          ##
          # Elixirs above this aren't available on ubuntu-20.04
          ##

          # ELIXIR 1.15 (OTP 26-24)
          - elixir: "1.15.x"
            otp: "26.x"
            os: "ubuntu-24.04"
            type: required
          - elixir: "1.15.x"
            otp: "26.x"
            os: "ubuntu-22.04"
            type: required
          - elixir: "1.15.x"
            otp: "26.x"
            os: "ubuntu-20.04"
            type: required
          - elixir: "1.15.x"
            otp: "26.x"
            os: "windows-2025"
            type: required
          - elixir: "1.15.x"
            otp: "26.x"
            os: "windows-2022"
            type: required
          - elixir: "1.15.x"
            otp: "26.x"
            os: "macOS-15"
            type: required
          - elixir: "1.15.x"
            otp: "26.x"
            os: "macOS-14"
            type: required
          - elixir: "1.15.x"
            otp: "25.x"
            os: "ubuntu-24.04"
            type: required
          - elixir: "1.15.x"
            otp: "25.x"
            os: "ubuntu-22.04"
            type: required
          - elixir: "1.15.x"
            otp: "25.x"
            os: "ubuntu-20.04"
            type: required
          - elixir: "1.15.x"
            otp: "25.x"
            os: "windows-2025"
            type: required
          - elixir: "1.15.x"
            otp: "25.x"
            os: "windows-2022"
            type: required
          - elixir: "1.15.x"
            otp: "25.x"
            os: "macOS-15"
            type: required
          - elixir: "1.15.x"
            otp: "25.x"
            os: "macOS-14"
            type: required
          - elixir: "1.15.x"
            otp: "24.x"
            os: "ubuntu-24.04"
            type: required
          - elixir: "1.15.x"
            otp: "24.x"
            os: "ubuntu-22.04"
            type: required
          - elixir: "1.15.x"
            otp: "24.x"
            os: "ubuntu-20.04"
            type: required
          - elixir: "1.15.x"
            otp: "24.x"
            os: "windows-2025"
            type: required
          - elixir: "1.15.x"
            otp: "24.x"
            os: "windows-2022"
            type: required

          ####
          # UNMAINTAINED ELIXIRS
          ##

          ##
          # OTPs <24 below this aren't available on ubuntu >20 images
          ##

          # ELIXIR 1.14 (OTP 26-23)
          - elixir: "1.14.x"
            otp: "26.x"
            os: "ubuntu-24.04"
            type: required
          - elixir: "1.14.x"
            otp: "26.x"
            os: "ubuntu-22.04"
            type: required
          - elixir: "1.14.x"
            otp: "26.x"
            os: "ubuntu-20.04"
            type: required
          - elixir: "1.14.x"
            otp: "26.x"
            os: "windows-2025"
            type: required
          - elixir: "1.14.x"
            otp: "26.x"
            os: "windows-2022"
            type: required
          - elixir: "1.14.x"
            otp: "26.x"
            os: "macOS-15"
            type: required
          - elixir: "1.14.x"
            otp: "26.x"
            os: "macOS-14"
            type: required
          - elixir: "1.14.x"
            otp: "25.x"
            os: "ubuntu-24.04"
            type: required
          - elixir: "1.14.x"
            otp: "25.x"
            os: "ubuntu-22.04"
            type: required
          - elixir: "1.14.x"
            otp: "25.x"
            os: "ubuntu-20.04"
            type: required
          - elixir: "1.14.x"
            otp: "25.x"
            os: "windows-2025"
            type: required
          - elixir: "1.14.x"
            otp: "25.x"
            os: "windows-2022"
            type: required
          - elixir: "1.14.x"
            otp: "25.x"
            os: "macOS-15"
            type: required
          - elixir: "1.14.x"
            otp: "25.x"
            os: "macOS-14"
            type: required
          - elixir: "1.14.x"
            otp: "24.x"
            os: "ubuntu-24.04"
            type: required
          - elixir: "1.14.x"
            otp: "24.x"
            os: "ubuntu-22.04"
            type: required
          - elixir: "1.14.x"
            otp: "24.x"
            os: "ubuntu-20.04"
            type: required
          - elixir: "1.14.x"
            otp: "24.x"
            os: "windows-2025"
            type: required
          - elixir: "1.14.x"
            otp: "24.x"
            os: "windows-2022"
            type: required
          - elixir: "1.14.x"
            otp: "23.x"
            os: "ubuntu-20.04"
            type: required
          - elixir: "1.14.x"
            otp: "23.x"
            os: "windows-2025"
            type: required
          - elixir: "1.14.x"
            otp: "23.x"
            os: "windows-2022"
            type: required

          # ELIXIR 1.13 (OTP 25-22)
          - elixir: "1.13.x"
            otp: "25.x"
            os: "ubuntu-24.04"
            type: required
          - elixir: "1.13.x"
            otp: "25.x"
            os: "ubuntu-22.04"
            type: required
          - elixir: "1.13.x"
            otp: "25.x"
            os: "ubuntu-20.04"
            type: required
          - elixir: "1.13.x"
            otp: "25.x"
            os: "windows-2025"
            type: required
          - elixir: "1.13.x"
            otp: "25.x"
            os: "windows-2022"
            type: required
          - elixir: "1.13.x"
            otp: "25.x"
            os: "macOS-15"
            type: required
          - elixir: "1.13.x"
            otp: "25.x"
            os: "macOS-14"
            type: required
          - elixir: "1.13.x"
            otp: "24.x"
            os: "ubuntu-24.04"
            type: required
          - elixir: "1.13.x"
            otp: "24.x"
            os: "ubuntu-22.04"
            type: required
          - elixir: "1.13.x"
            otp: "24.x"
            os: "ubuntu-20.04"
            type: required
          - elixir: "1.13.x"
            otp: "24.x"
            os: "windows-2025"
            type: required
          - elixir: "1.13.x"
            otp: "24.x"
            os: "windows-2022"
            type: required
          - elixir: "1.13.x"
            otp: "23.x"
            os: "ubuntu-20.04"
            type: required
          - elixir: "1.13.x"
            otp: "23.x"
            os: "windows-2025"
            type: required
          - elixir: "1.13.x"
            otp: "23.x"
            os: "windows-2022"
            type: required
          - elixir: "1.13.x"
            otp: "22.x"
            os: "ubuntu-20.04"
            type: required
          - elixir: "1.13.x"
            otp: "22.x"
            os: "windows-2025"
            type: required
          - elixir: "1.13.x"
            otp: "22.x"
            os: "windows-2022"
            type: required

          # ELIXIR 1.12 (OTP 24-22)
          - elixir: "1.12.x"
            otp: "24.x"
            os: "ubuntu-24.04"
            type: required
          - elixir: "1.12.x"
            otp: "24.x"
            os: "ubuntu-22.04"
            type: required
          - elixir: "1.12.x"
            otp: "24.x"
            os: "ubuntu-20.04"
            type: required
          - elixir: "1.12.x"
            otp: "24.x"
            os: "windows-2025"
            type: required
          - elixir: "1.12.x"
            otp: "24.x"
            os: "windows-2022"
            type: required
          - elixir: "1.12.x"
            otp: "23.x"
            os: "ubuntu-20.04"
            type: required
          - elixir: "1.12.x"
            otp: "23.x"
            os: "windows-2025"
            type: required
          - elixir: "1.12.x"
            otp: "23.x"
            os: "windows-2022"
            type: required
          - elixir: "1.12.x"
            otp: "22.x"
            os: "ubuntu-20.04"
            type: required
          - elixir: "1.12.x"
            otp: "22.x"
            os: "windows-2025"
            type: required
          - elixir: "1.12.x"
            otp: "22.x"
            os: "windows-2022"
            type: required

          ####
          # ORIGINAL TEST MATRIX
          #
          # Project was originally only tested on Elixir 1.10-1.11, OTP 22-23, so we should test back to then until a breaking release
          #  See: https://github.com/asummers/erlex/blob/0548765838a08583c83d72d208fde112104a3d2b/.github/workflows/pulls.yml#L11-L12
          # Project was originally claiming it supports back to Elixir 1.6, so we should test back to then until a breaking release
          #  See: https://github.com/asummers/erlex/blob/master/mix.exs#L11
          # OTP 21.x and older is retired in erlef/setup-beam, so we omit that in these matrices.
          ##

          # ELIXIR 1.11 (OTP 23-21)
          - elixir: "1.11.x"
            otp: "23.x"
            os: "ubuntu-20.04"
            type: required
          - elixir: "1.11.x"
            otp: "23.x"
            os: "windows-2025"
            type: required
          - elixir: "1.11.x"
            otp: "23.x"
            os: "windows-2022"
            type: required
          - elixir: "1.11.x"
            otp: "22.x"
            os: "ubuntu-20.04"
            type: required
          - elixir: "1.11.x"
            otp: "22.x"
            os: "windows-2025"
            type: required
          - elixir: "1.11.x"
            otp: "22.x"
            os: "windows-2022"
            type: required
          # Retired from erlef/setup-beam: OTP < 22.x
          # - elixir: "1.11.x"
          #   otp: "21.x"
          #   os: "ubuntu-20.04"
          #   type: required
          # - elixir: "1.11.x"
          #   otp: "21.x"
          #   os: "windows-2025"
          #   type: required
          # - elixir: "1.11.x"
          #   otp: "21.x"
          #   os: "windows-2022"
          #   type: required

          # ELIXIR 1.10 (OTP 23-21)
          - elixir: "1.10.x"
            otp: "23.x"
            os: "ubuntu-20.04"
            type: required
          - elixir: "1.10.x"
            otp: "23.x"
            os: "windows-2025"
            type: required
          - elixir: "1.10.x"
            otp: "23.x"
            os: "windows-2022"
            type: required
          - elixir: "1.10.x"
            otp: "22.x"
            os: "ubuntu-20.04"
            type: required
          - elixir: "1.10.x"
            otp: "22.x"
            os: "windows-2025"
            type: required
          - elixir: "1.10.x"
            otp: "22.x"
            os: "windows-2022"
            type: required
          # Retired from erlef/setup-beam: OTP < 22.x
          # - elixir: "1.10.x"
          #   otp: "21.x"
          #   os: "ubuntu-20.04"
          #   type: required
          # - elixir: "1.10.x"
          #   otp: "21.x"
          #   os: "windows-2025"
          #   type: required
          # - elixir: "1.10.x"
          #   otp: "21.x"
          #   os: "windows-2022"
          #   type: required

          ##
          # OTPs <21 below this aren't available on windows images
          ##

          # ELIXIR 1.9 (OTP 22-20)
          - elixir: "1.9.x"
            otp: "22.x"
            os: "ubuntu-20.04"
            type: required
          # Retired from erlef/setup-beam: OTP < 22.x
          # - elixir: "1.9.x"
          #   otp: "21.x"
          #   os: "ubuntu-20.04"
          #   type: required
          # - elixir: "1.9.x"
          #   otp: "20.x"
          #   os: "ubuntu-20.04"
          #   type: required

          # ELIXIR 1.8 (OTP 22-20)
          - elixir: "1.8.x"
            otp: "22.x"
            os: "ubuntu-20.04"
            type: required
          # Retired from erlef/setup-beam: OTP < 22.x
          # - elixir: "1.8.x"
          #   otp: "21.x"
          #   os: "ubuntu-20.04"
          #   type: required
          # - elixir: "1.8.x"
          #   otp: "20.x"
          #   os: "ubuntu-20.04"
          #   type: required

          ##
          # Elixirs below this point work on OTP < 20, which requires ubuntu-18.04
          #  which is no longer supported by GitHub actions, so we skip them
          ##

          # ELIXIR 1.7 (OTP 22-19)
          - elixir: "1.7.x"
            otp: "22.x"
            os: "ubuntu-20.04"
            type: required
          # Retired from erlef/setup-beam: OTP < 22.x
          # - elixir: "1.7.x"
          #   otp: "21.x"
          #   os: "ubuntu-20.04"
          #   type: required
          # - elixir: "1.7.x"
          #   otp: "20.x"
          #   os: "ubuntu-20.04"
          #   type: required

          # ELIXIR 1.6 (OTP 21-19)
          # Retired from erlef/setup-beam: OTP < 22.x
          # - elixir: "1.6.x"
          #   otp: "21.x"
          #   os: "ubuntu-20.04"
          #   type: required
          # - elixir: "1.6.x"
          #   otp: "20.x"
          #   os: "ubuntu-20.04"
          #   type: required

    steps:
      - uses: actions/checkout@v4

      - name: Install Erlang & Elixir
        id: beam-versions
        uses: erlef/setup-beam@v1
        with:
          elixir-version: ${{ matrix.elixir }}
          otp-version: ${{ matrix.otp }}

      - name: Restore mix dependency installation cache
        id: mix-deps-get-cache
        uses: actions/cache@v4
        with:
          path: |
            deps
            mix.lock
          key: cache-${{ vars.CACHE_VERSION }}-os-${{ runner.os }}-otp-${{ steps.beam-versions.outputs.otp-version }}-elixir-${{ steps.beam-versions.outputs.elixir-version }}-env-${{ env.MIX_ENV }}-mix-deps-get-mix-exs-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.exs')) }}

      - name: Install mix dependencies
        if: steps.mix-deps-get-cache.outputs.cache-hit != 'true'
        run: mix deps.get

      - name: Restore mix dependency compilation cache
        id: mix-deps-compile-cache
        uses: actions/cache@v4
        with:
          path: _build
          key: cache-${{ vars.CACHE_VERSION }}-os-${{ runner.os }}-otp-${{ steps.beam-versions.outputs.otp-version }}-elixir-${{ steps.beam-versions.outputs.elixir-version }}-env-${{ env.MIX_ENV }}-mix-deps-compile-mix-lock-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}

      - name: Compile mix dependencies
        if: steps.mix-deps-compile-cache.outputs.cache-hit != 'true'
        run: mix deps.compile

      - name: Restore mix typecheck cache
        id: mix-typecheck-cache
        uses: actions/cache@v4
        with:
          path: priv/plts
          key: cache-${{ vars.CACHE_VERSION }}-os-${{ runner.os }}-otp-${{ steps.beam-versions.outputs.otp-version }}-elixir-${{ steps.beam-versions.outputs.elixir-version }}-env-${{ env.MIX_ENV }}-mix-typecheck

      - name: Setup typechecking
        if: steps.mix-typecheck-cache.outputs.cache-hit != 'true'
        run: mix typecheck.build-cache

      - name: Run typecheck tasks
        run: mix typecheck

  lints:
    name: Linting
    runs-on: ${{ vars.PREFERRED_OS }}
    env:
      MIX_ENV: test

    steps:
      - uses: actions/checkout@v4

      - name: Install Erlang & Elixir
        id: beam-versions
        uses: erlef/setup-beam@v1
        with:
          elixir-version: ${{ vars.PREFERRED_ELIXIR }}
          otp-version: ${{ vars.PREFERRED_OTP }}

      - name: Restore mix dependency installation cache
        id: mix-deps-get-cache
        uses: actions/cache@v4
        with:
          path: deps
          key: cache-${{ vars.CACHE_VERSION }}-os-${{ runner.os }}-otp-${{ steps.beam-versions.outputs.otp-version }}-elixir-${{ steps.beam-versions.outputs.elixir-version }}-env-${{ env.MIX_ENV }}-mix-deps-get-mix-lock-file-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}

      - name: Install mix dependencies
        if: steps.mix-deps-get-cache.outputs.cache-hit != 'true'
        run: mix deps.get

      - name: Restore mix dependency compilation cache
        id: mix-deps-compile-cache
        uses: actions/cache@v4
        with:
          path: _build
          key: cache-${{ vars.CACHE_VERSION }}-os-${{ runner.os }}-otp-${{ steps.beam-versions.outputs.otp-version }}-elixir-${{ steps.beam-versions.outputs.elixir-version }}-env-${{ env.MIX_ENV }}-mix-deps-compile-mix-lock-file-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}

      - name: Compile mix dependencies
        if: steps.mix-deps-compile-cache.outputs.cache-hit != 'true'
        run: mix deps.compile

      - name: Run linter tasks
        run: mix lint

  hex:
    runs-on: ${{ vars.PREFERRED_OS }}
    name: Publishing to hex.pm

    needs:
      - tests
      - types
      - lints

    env:
      HEX_API_KEY: ${{ secrets.HEX_API_KEY }}
      MIX_ENV: prod

    steps:
      - uses: actions/checkout@v2

      - name: Install Erlang & Elixir
        id: beam-versions
        uses: erlef/setup-beam@v1
        with:
          elixir-version: ${{ vars.PREFERRED_ELIXIR }}
          otp-version: ${{ vars.PREFERRED_OTP }}

      - name: Restore mix dependency installation cache
        id: mix-deps-get-cache
        uses: actions/cache@v4
        with:
          path: deps
          key: cache-${{ vars.CACHE_VERSION }}-os-${{ runner.os }}-otp-${{ steps.beam-versions.outputs.otp-version }}-elixir-${{ steps.beam-versions.outputs.elixir-version }}-env-${{ env.MIX_ENV }}-mix-deps-get-mix-lock-file-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}

      - name: Install mix dependencies
        if: steps.mix-deps-get-cache.outputs.cache-hit != 'true'
        run: mix deps.get

      - name: Restore mix dependency compilation cache
        id: mix-deps-compile-cache
        uses: actions/cache@v4
        with:
          path: _build
          key: cache-${{ vars.CACHE_VERSION }}-os-${{ runner.os }}-otp-${{ steps.beam-versions.outputs.otp-version }}-elixir-${{ steps.beam-versions.outputs.elixir-version }}-env-${{ env.MIX_ENV }}-mix-deps-compile-mix-lock-file-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}

      - name: Compile mix dependencies
        if: steps.mix-deps-compile-cache.outputs.cache-hit != 'true'
        run: mix deps.compile

      - name: Publish package to hex.pm
        run: mix hex.publish --yes

  results:
    name: Publish Package Results
    runs-on: ${{ vars.PREFERRED_OS }}

    if: ${{ always() }}
    needs:
      - tests
      - types
      - lints
      - hex

    steps:
      - name: Publish Package Succeeded
        if: ${{ needs.tests.result == 'success' && needs.types.result == 'success' && needs.lints.result == 'success' && needs.hex.result == 'success' }}
        run: exit 0

      - name: Publish Package Failed
        if: ${{ needs.tests.result == 'failure' || needs.types.result == 'failure' || needs.lints.result == 'failure' || needs.hex.result == 'failure' }}
        run: exit 1
